name: iOS Build (No Code Signing)

on:
  push:
    branches:
      - main

jobs:
  build_ios:
    runs-on: macos-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: 'stable'

      - name: Install dependencies
        run: flutter pub get

      - name: Build iOS (No Code Signing)
        run: flutter build ios --no-codesign

      - name: Archive Xcode Project Without Signing
        run: |
          cd ios
          xcodebuild build \
            -workspace Runner.xcworkspace \
            -scheme Runner \
            -sdk iphoneos \
            -configuration Release \
            CODE_SIGNING_ALLOWED=NO

      - name: Upload Build Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: ios-build
          path: build/ios/iphoneos
