name: iOS-ipa-build

on:
  workflow_dispatch:

jobs:
  build-ios:
    name: 🎉 iOS Build
    runs-on: macos-latest

    permissions:
      contents: write  # Grants required permissions for uploading assets

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
          architecture: x64

      - name: Upgrade Flutter
        run: flutter upgrade

      - name: Print Flutter & Xcode Versions
        run: |
          flutter --version
          xcodebuild -version

      - name: Clean project
        run: flutter clean

      - name: Get dependencies
        run: flutter pub get

      - name: Ensure iOS Deployment Target is 14.0
        run: |
          if ! grep -q 'platform :ios' ios/Podfile; then
            echo 'platform :ios, "14.0"' >> ios/Podfile
          else
            sed -i '' 's/platform :ios, .*/platform :ios, "14.0"/' ios/Podfile
          fi
          cat ios/Podfile  # Print to verify change

      - name: Remove existing Pods and Lockfile
        run: |
          rm -rf ios/Pods ios/Podfile.lock ~/Library/Developer/Xcode/DerivedData

      - name: Deintegrate CocoaPods
        run: pod deintegrate
        working-directory: ios

      - name: Update CocoaPods and Install Dependencies
        run: |
          pod repo update
          pod install --verbose
        working-directory: ios

      - name: Build iOS app (without codesign)
        run: flutter build ios --release --no-codesign

      - name: Create Payload directory for IPA
        run: mkdir -p build/ios/iphoneos/Payload

      - name: Move app to Payload directory
        run: mv build/ios/iphoneos/Runner.app build/ios/iphoneos/Payload/

      - name: Create IPA file
        run: |
          cd build/ios/iphoneos
          zip -qq -r -9 FlutterIpaExport.ipa Payload

      - name: Upload IPA to GitHub Releases
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: build/ios/iphoneos/FlutterIpaExport.ipa
          tag: ${{ github.ref_name }}
          overwrite: true
          body: "Automated iOS build release 🚀"
